### ISSUE TITLE
Make it easier to use Chrome’s device orientation emulation

### ISSUE THREAD

**Issue by lydell** [richtr/Full-Tilt#7]
Chrome’s devtools are able to emulate device orientation on a desktop computer that lacks orientation hardware, which is very handy for development. However, this is not possible if you use the recommended `FULLTILT.getDeviceOrientation( [options] )` and `FULLTILT.getDeviceMotion( [options] )` functions, because they will just report that “Device{Orientation,Motion} is not supported”.

You _could_ use the `new FULLTILT.Device{Orientation,Motion}( [options] )` constructors directly for this case, but the down-side is that those constructors return objects directly, while the `.get*` methods return Promises, so switching to the constructors for development isn’t really practical because of the flow control differences.

It would be great if it was easier to make use of Chrome’s devtools.

**Comment by fergusg** [comment]
I found that you can use emulation if you enable it *after* initializing  FULLTILT.   Still a bit awkward as one has to remember to disable-reload-enable on each dev. cycle, but better than nothing.

**Comment by greggman** [comment]
Maybe this is what you were saying but basically if I move the emulator within 1 second of starting my app it works. After 1 second it assumes there's no sensor. An override would be good too but for now just remembering to nudge the emulator after refresh works for me.

**Comment by richtr** [comment]
I am looking in to enabling this emulation once again. Last time I looked at this I didn't get very far because once the sensor check completes a lot of the subsequent code paths tend to rely on device orientation data being present (which would not be the case with emulation unless you've enabled that emulation manually in the console).

I'm pleased that there is a way to 'trick' the library but you should also be aware of https://github.com/richtr/Full-Tilt/issues/12 which makes deviceorientation emulation through Chrome very unreliable. Building a device orientation web app against the Chrome emulator is not going to produce the right output on mobile devices. The only way to currently test this is against real devices (browsers on real iOS and Android devices).

**Comment by fergusg** [comment]
Mostly all I care about is to get any orientation events sent, to check that mu apps  effects are triggered

**Comment by richtr** [comment]
So I recently created an in-browser Device Orientation emulator called [doe](https://github.com/richtr/doe) that should be used to debug Full-Tilt based web applications from now on due to numerous problems I had been having with the Chrome Device Orientation Emulation Tool.

There are a number of serious issues with the Chrome device orientation emulation tool (see https://github.com/richtr/Full-Tilt/issues/12). It does not reflect how the user holds a device, how the device really rotates in physical space and it does not account for any rolling of a device's screen.

[doe](https://github.com/richtr/doe) does not suffer from any of those issues. Please consider using that from now on and if you like it, tell other people it exists and kicks ass :)
